@api = http://localhost:3000/details

### Get all tasks
{{api}}

### create a new task
POST {{api}}
Content-Type: application/json

{
 "IdAsignacion" : 1,
 "CodigoGrupoRecurso": "ASI_DET_EXAMPLE",
 "CodigoOpcionRecurso" : 1,
 "Respuesta" : "BUENO"
}

### get a single task
{{api}}/5

### delete a single user
DELETE {{api}}/4

### get count
{{api}}/count

### update task
PUT {{api}}/5
Content-Type: application/json

{
  "title": "some new title 5 edited",
  "description": "some new description 5 edit"
}


//SELECT IF(MAX(IdAsignacion), MAX(IdAsignacion), 0) AS 'Cantidad' FROM asignacionvehiculorespuesta WHERE CodigoVehiculo = 1

// Revisar libreria react-usestateref